.TH "python/afficheHough.py" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/afficheHough.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBafficheHough\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBafficheHough\&.proches\fP (p1, p2)"
.br
.ti -1c
.RI "def \fBafficheHough\&.clusterGen\fP (first, tab)"
.br
.ti -1c
.RI "def \fBafficheHough\&.clustering\fP (rho_theta)"
.br
.ti -1c
.RI "def \fBafficheHough\&.filterClusters\fP (clusters)"
.br
.ti -1c
.RI "def \fBafficheHough\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
