.TH "afficheHough" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
afficheHough
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBproches\fP (p1, p2)"
.br
.ti -1c
.RI "def \fBclusterGen\fP (first, tab)"
.br
.ti -1c
.RI "def \fBclustering\fP (rho_theta)"
.br
.ti -1c
.RI "def \fBfilterClusters\fP (clusters)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def afficheHough\&.clusterGen ( first,  tab)"

.PP
Definition at line 15 of file afficheHough\&.py\&.
.SS "def afficheHough\&.clustering ( rho_theta)"

.PP
Definition at line 23 of file afficheHough\&.py\&.
.SS "def afficheHough\&.filterClusters ( clusters)"

.PP
Definition at line 36 of file afficheHough\&.py\&.
.SS "def afficheHough\&.main ()"

.PP
Definition at line 45 of file afficheHough\&.py\&.
.SS "def afficheHough\&.proches ( p1,  p2)"

.PP
Definition at line 6 of file afficheHough\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
