.TH "include/dbscan.hpp" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/dbscan.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'line\&.hpp'\fP
.br
\fC#include 'ClusteredLine\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDBSCAN\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNCLASSIFIED\fP   \-1"
.br
.ti -1c
.RI "#define \fBNOISE\fP   \-2"
.br
.ti -1c
.RI "#define \fBSUCCESS\fP   0"
.br
.ti -1c
.RI "#define \fBFAILURE\fP   \-3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FAILURE   \-3"

.PP
Definition at line 13 of file dbscan\&.hpp\&.
.SS "#define NOISE   \-2"

.PP
Definition at line 11 of file dbscan\&.hpp\&.
.SS "#define SUCCESS   0"

.PP
Definition at line 12 of file dbscan\&.hpp\&.
.SS "#define UNCLASSIFIED   \-1"

.PP
Definition at line 10 of file dbscan\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
