.TH "python/hough.py" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/hough.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhough\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhough\&.hough\fP (theta, x, y)"
.br
.ti -1c
.RI "def \fBhough\&.draw\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
