.TH "hough" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hough
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhough\fP (theta, x, y)"
.br
.ti -1c
.RI "def \fBdraw\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def hough\&.draw ()"

.PP
Definition at line 15 of file hough\&.py\&.
.SS "def hough\&.hough ( theta,  x,  y)"

.PP
Definition at line 11 of file hough\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
