.TH "include/InterestPoints.hpp" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/InterestPoints.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <opencv2/features2d\&.hpp>\fP
.br
\fC#include <opencv2/xfeatures2d/nonfree\&.hpp>\fP
.br
\fC#include 'InterestPoint\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdefals::InterestPoints\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdefals\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
