.TH "src/line.cpp" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/line.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/line\&.hpp'\fP
.br
\fC#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Mat \fBfullPlane\fP (const Mat &src, std::vector< \fBLine\fP > &lines, int thickness)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Mat fullPlane (const Mat & src, std::vector< \fBLine\fP > & lines, int thickness)"

.PP
Definition at line 210 of file line\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
