.TH "include/line.hpp" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/line.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <opencv2/features2d\&.hpp>\fP
.br
\fC#include <opencv2/xfeatures2d/nonfree\&.hpp>\fP
.br
\fC#include 'InterestPoint\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdefals::Line\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdefals\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBdefals::operator==\fP (const Line &first, const Line &second)"
.br
.ti -1c
.RI "bool \fBdefals::operator!=\fP (const Line &first, const Line &second)"
.br
.ti -1c
.RI "std::ostream & \fBdefals::operator<<\fP (std::ostream &os, const Line &line)"
.br
.ti -1c
.RI "cv::Mat \fBdefals::fullPlane\fP (const cv::Mat &src, std::vector< Line > &lines, int thickness=3)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
