.TH "src/main.cpp" 3 "Tue Jul 7 2020" "copyMoveCheck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <boost/log/core\&.hpp>\fP
.br
\fC#include <boost/log/expressions\&.hpp>\fP
.br
\fC#include <boost/log/trivial\&.hpp>\fP
.br
\fC#include '\&.\&./include/copyMoveDetector\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_logger\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_logger ()"

.PP
Definition at line 12 of file main\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 19 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for copyMoveCheck from the source code\&.
